### ISSUE TITLE
There is chrome devtools for redux-zero?

### ISSUE THREAD

**Issue by ruslan-mystore** [concretesolutions/redux-zero#19]
There is chrome devtools for redux-zero?

**Comment by matheusml** [comment]
Not yet @ruslan-mystore, the project is brand new.
But if you want to help us build one it'll be fantastic!

**Comment by blackpr** [comment]
If we don't have reducers and a dispatcher does this mean that there is no way to capture the actions? 
Also does it means that we cannot send the actions to redux devtools?

**Comment by blackpr** [comment]
We can record the current state to redux devtools and jump to specific state.
In store.js: 
```js
const devTools = window.__REDUX_DEVTOOLS_EXTENSION__.connect();
devTools.send('initialState', initialState);

devTools.subscribe((message) => {
  if (message.type === 'DISPATCH' && message.payload.type === 'JUMP_TO_ACTION') {
    store.setState(JSON.parse(message.state));
  }
});

store.subscribe(state => {
  devTools.send('stateChanges', state);
});
```

**Comment by matheusml** [comment]
Not yet @blackpr 

But after we have a solution to [this problem](https://github.com/concretesolutions/redux-zero/issues/16), maybe that's going to be possible. I think it's great that the community is already thinking about this, but right now we have two major concerns:
- [Add Preact bindings](https://github.com/concretesolutions/redux-zero/issues/20)
- [Bind actions instead of coupling them to the store](https://github.com/concretesolutions/redux-zero/issues/16)

**Comment by blackpr** [comment]
sure @matheusml No problem :)

**Comment by developit** [comment]
@matheusml - I wonder if it'd be worth throwing this basic version in as an entrypoint?

**Comment by matheusml** [comment]
@developit - Isn't a problem that is coupled to Redux Devtools?

**Comment by blackpr** [comment]
Now that we have middleware support https://github.com/concretesolutions/redux-zero/issues/36 we can use something like this https://codesandbox.io/s/qvnm8w597q to capture actions and state to redux devtools

**Comment by matheusml** [comment]
I agree with you @blackpr 

Could you please open an issue/PR with this?

**Comment by blackpr** [comment]
I dont think I know how to do this.
Sorry :(
