### ISSUE TITLE
Create an example with React Native

### ISSUE THREAD

**Issue by matheusml** [concretesolutions/redux-zero#35]
#32

**Comment by guilhermefloriani** [comment]
I wrote a counter app example yesterday like I comment on #32, but there is no difference from the web version, except that instead of using `ReactDOM` to render your main component, you register it using `AppRegistry` of `react-native`, but this has nothing to do with redux.

If I write an code example it will be almost equal the code in `README.md`, but if it is really necessary I can create an repository example and link it.

**Comment by matheusml** [comment]
@guilhermefloriani 

The ideal version should be an `examples/` folder in the root of this repository. Like this:

```
examples/
  react/
  react-native/
  preact/
```

So that in the README, we can create a new section linking to all the examples, like this:

**More examples**
- [React]()
- [Preact]()
- [React Native]()

See what I mean?

**Comment by guilhermefloriani** [comment]
Sure, seems good.
I'll try to do it tonight.

**Comment by matheusml** [comment]
Thanks @guilhermefloriani 
That will be awesome. :100:

**Comment by guilhermefloriani** [comment]
What do you think @matheusml ?
