### ISSUE TITLE
Async example only updates state once

### ISSUE THREAD

**Issue by esperancaJS** [concretesolutions/redux-zero#96]
Async actions seem to not update the state or register an action on the chrome dev tools after the async request.

This was attempted with the example on the README and on [this thread](https://github.com/concretesolutions/redux-zero/issues/75).

**Comment by matheusml** [comment]
@PedroEsperanca I think that the state is being updated but the DevTools are not reflecting it.

Can you setup an example showing that the async request isn't working **without** the DevTools?

@Kiho maybe we got something wrong on the DevTools?

**Comment by Kiho** [comment]
It's hard to know what's really happen without repro is provided. I guess problem related to the comment in this thread https://github.com/concretesolutions/redux-zero/issues/36#issuecomment-346836408
If that's the case then need to make actions are unique and need to be saved in it's own files.
I can't do not much thing here because it's caused by no key is associated to action in redux-zero.

**Comment by PedroEsperanca** [comment]
thanks for the quick response!

You are right, it's just a little quirk with the dev tools. The actual store updates fine.

Here a full example: https://github.com/PedroEsperanca/redux-zero-async-example

**Comment by Kiho** [comment]
I missed to test asynchronous actions during development. I will try to find out solution in short time.

**Comment by Kiho** [comment]
Hi @matheusml 
I found solution for async actions here 
https://github.com/Kiho/redux-zero/commit/d63bacaa05cf3b5f0935a3305a15d46ec4284e76
I can make PR if you like it.
cc @PedroEsperanca

**Comment by matheusml** [comment]
Great @Kiho! Please open a PR with this fix.
